# Generated by Django 3.0.4 on 2021-03-27 12:44

from django.db import migrations
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='used',
            field=payments.models.VolumeUnitField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='watertransaction',
            name='dispensed',
            field=payments.models.VolumeUnitField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='watertransaction',
            name='request',
            field=payments.models.VolumeUnitField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
