# Generated by Django 3.0.4 on 2021-03-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mac_address',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
